# Generated by Django 5.2.17 on 2026-08-19 18:57

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('maps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('flag', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'names',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aat_id', models.IntegerField(unique=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=100)),
                ('term_full', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=3000)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'placetypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('year_pub', models.IntegerField(null=True)),
                ('cite_uri', models.URLField(null=True)),
                ('cite_text', models.CharField(max_length=2044)),
                ('tiles', models.BooleanField(default=False)),
                ('when', models.JSONField(null=True)),
                ('when_constant', models.BooleanField(default=True)),
                ('minzoom', models.CharField(max_length=2, null=True)),
                ('maxzoom', models.CharField(max_length=2, null=True)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=11), null=True, size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('placetype', models.CharField(max_length=20)),
                ('jsonb', models.JSONField(blank=True, null=True)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geom_line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('geom_poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(db_column='map', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.map')),
                ('src_name', models.ForeignKey(db_column='src_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_name', to='main.name')),
            ],
            options={
                'db_table': 'features',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapPlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.map')),
                ('placetype', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.placetype')),
            ],
            options={
                'db_table': 'map_placetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=20)),
                ('uri', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='map',
            name='project',
            field=models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='main.project'),
        ),
        migrations.CreateModel(
            name='ProjectPlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(max_length=100)),
                ('aattype', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.placetype', to_field='aat_id')),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'db_table': 'project_placetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('owner', 'Owner'), ('member', 'Team Member')], max_length=20)),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.project')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_user',
                'managed': True,
            },
        ),
    ]
