# Generated by Django 5.2.17 on 2026-08-31 00:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aat_id', models.IntegerField(unique=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(max_length=100)),
                ('term_full', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=3000)),
                ('fclass', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'placetypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=20)),
                ('uri', models.URLField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectPlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(max_length=100)),
                ('aattype', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.placetype', to_field='aat_id')),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'db_table': 'project_placetype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('owner', 'Owner'), ('member', 'Team Member')], max_length=20)),
                ('project', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.project')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ingest_uri', models.URLField(max_length=2048)),
                ('ingest_kind', models.CharField(choices=[('manifest', 'IIIF Presentation Manifest'), ('image_service', 'IIIF Image service / info.json')], max_length=16)),
                ('iiif_version', models.CharField(blank=True, max_length=8)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('raw_document', models.TextField(blank=True)),
                ('normalization_log', models.JSONField(blank=True, default=list)),
                ('iiif_label', models.CharField(blank=True, max_length=1000)),
                ('iiif_metadata', models.JSONField(blank=True, default=list)),
                ('iiif_rights', models.CharField(blank=True, max_length=500)),
                ('iiif_summary', models.TextField(blank=True)),
                ('iiif_required_statement', models.JSONField(blank=True, null=True)),
                ('nav_date', models.CharField(blank=True, max_length=64)),
                ('label', models.SlugField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('citation', models.TextField(blank=True)),
                ('citation_uri', models.URLField(blank=True, max_length=1024)),
                ('year_pub', models.IntegerField(blank=True, null=True)),
                ('when', models.JSONField(blank=True, null=True)),
                ('scope_ccodes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None)),
                ('scope_bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('scope_note', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.project')),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['project', 'label', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=0)),
                ('canvas_uri', models.URLField(blank=True, max_length=2048)),
                ('image_service_uri', models.URLField(max_length=2048)),
                ('info_json', models.JSONField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=1000)),
                ('when', models.JSONField(blank=True, null=True)),
                ('needs_metadata', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.source')),
            ],
            options={
                'db_table': 'map_images',
                'ordering': ['source', 'seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unstarted', 'Not started'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='unstarted', max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_images', to=settings.AUTH_USER_MODEL)),
                ('image', models.OneToOneField(db_column='image', on_delete=django.db.models.deletion.CASCADE, related_name='workstate', to='main.mapimage')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'work_states',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('label', ''), _negated=True), fields=('project', 'label'), name='uniq_source_label_per_project'),
        ),
        migrations.AddConstraint(
            model_name='mapimage',
            constraint=models.UniqueConstraint(fields=('source', 'seq'), name='uniq_mapimage_seq_per_source'),
        ),
    ]
