# Generated by Django 5.2.17 on 2026-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapimage',
            name='quality_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
