# Generated by Django 5.2.17 on 2026-08-31 17:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mapimage_quality_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplacetype',
            options={'managed': True, 'ordering': ['project', 'source_label']},
        ),
        migrations.AlterField(
            model_name='projectplacetype',
            name='aattype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.placetype', to_field='aat_id'),
        ),
        migrations.AlterField(
            model_name='projectplacetype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placetypes', to='main.project'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_type', models.CharField(choices=[('polygon', 'Polygon'), ('polyline', 'Polyline'), ('point', 'Point')], max_length=12)),
                ('feature_role', models.CharField(choices=[('region', 'Region'), ('label', 'Label'), ('boundary', 'Boundary'), ('site', 'Site')], max_length=12)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_normalized', models.CharField(blank=True, max_length=255)),
                ('certainty', models.CharField(blank=True, choices=[('certain', 'Certain'), ('likely', 'Likely'), ('uncertain', 'Uncertain')], max_length=12)),
                ('when', models.JSONField(blank=True, null=True)),
                ('w3c', models.JSONField(blank=True, default=dict)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(db_column='image', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='main.mapimage')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_modified', to=settings.AUTH_USER_MODEL)),
                ('placetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='main.projectplacetype')),
            ],
            options={
                'db_table': 'annotations',
                'ordering': ['image', 'created'],
                'managed': True,
            },
        ),
    ]
