# Generated by Django 5.2.17 on 2026-09-04 00:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def creator_role_to_owner(apps, schema_editor):
    """WO-0.5: TEAMROLES dropped 'creator'. Fold any existing rows into 'owner'
    (the dev DB has no ProjectUser rows yet; kept for correctness elsewhere)."""
    ProjectUser = apps.get_model('main', 'ProjectUser')
    ProjectUser.objects.filter(role='creator').update(role='owner')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projectplacetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(creator_role_to_owner, migrations.RunPython.noop),
        migrations.AddField(
            model_name='project',
            name='scope_bbox',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('annotator', 'Annotator')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together={('project', 'user')},
        ),
        migrations.CreateModel(
            name='MapImagePlacetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placetypes', to='main.mapimage')),
                ('placetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_scopes', to='main.projectplacetype')),
            ],
            options={
                'db_table': 'map_image_placetype',
                'managed': True,
                'unique_together': {('image', 'placetype')},
            },
        ),
    ]
