"""
Django settings for cpdraw project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(os.path.join(BASE_DIR, '.env'))

# GeoDjango native libs (see .env)
if os.environ.get('GDAL_LIBRARY_PATH'):
    GDAL_LIBRARY_PATH = os.environ['GDAL_LIBRARY_PATH']
if os.environ.get('GEOS_LIBRARY_PATH'):
    GEOS_LIBRARY_PATH = os.environ['GEOS_LIBRARY_PATH']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Real value lives in local_settings.py (gitignored), which overrides this.
SECRET_KEY = 'insecure-dev-key-set-a-real-one-in-local-settings-py'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL='/accounts/login/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.staticfiles',

    'rest_framework',
    'fontawesome_5',
    'django_vite',

    'accounts.apps.AccountsConfig',
    'main.apps.MainConfig',
    'api.apps.ApiConfig'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cpdraw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cpdraw.wsgi.application'

# Existing data (bregel schema) uses plain integer PKs; don't drift to BigAutoField.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'cpdraw/static/'),
    os.path.join(BASE_DIR, 'main/static/'),
    # Vite build output (WO-0.1). The ('frontend', ...) prefix means these are
    # served/collected under /static/frontend/..., matching Vite's `base` and
    # DJANGO_VITE static_url_prefix below. Directory is absent until the first
    # `pnpm --dir frontend build`; harmless when missing.
    ('frontend', os.path.join(BASE_DIR, 'frontend/dist/')),
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

try:
    from .local_settings import *
except ImportError:
    pass

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Connection params come from .env (PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD),
# matching the db_connect() convention used elsewhere. Placed after the
# local_settings import so it always wins over anything defined there.

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('PGDATABASE', 'cpdraw'),
        'USER': os.environ.get('PGUSER', ''),
        'PASSWORD': os.environ.get('PGPASSWORD', ''),
        'HOST': os.environ.get('PGHOST', 'localhost'),
        'PORT': os.environ.get('PGPORT', '5432'),
    }
}

# --- Frontend build pipeline (WO-0.1) ------------------------------------------
# Vite bundles the ESM-only Allmaps packages and the Svelte-authored Annotorious
# plugin code that the predecessor's script-tag/jQuery setup could not consume.
#
#   dev  (DEBUG=True):  run `pnpm --dir frontend dev` alongside runserver;
#                       django-vite points <script type="module"> at the Vite
#                       dev server on :5173 and injects the HMR client.
#   prod (DEBUG=False): run `pnpm --dir frontend build` before collectstatic;
#                       django-vite reads frontend/dist/.vite/manifest.json and
#                       emits hashed tags served from /static/frontend/.
#
# Placed after the local_settings import so dev_mode tracks the final DEBUG.
DJANGO_VITE = {
    'default': {
        'dev_mode': DEBUG,
        'dev_server_port': 5173,
        'static_url_prefix': 'frontend',
        'manifest_path': os.path.join(
            BASE_DIR, 'frontend', 'dist', '.vite', 'manifest.json'
        ),
    }
}

# Map the ERROR message level onto Bootstrap's "danger" alert class.
from django.contrib.messages import constants as _message_constants  # noqa: E402
MESSAGE_TAGS = {_message_constants.ERROR: 'danger'}
